Program REGIS01 ;
//FEITO PELO AMADISSSIMO ALUNO MANOEL
{F U P QUE LEIA UMA SERIE DE NOMES(MAX 35 CARACTERES) COM AS RESPECTIVAS NOTAS, ENCERRADA 
POR NOME =FIM. APOS O TERMINO DA LEITURA
MOSTRAR OS NOMES COM AS RESPECTIVAS NOTAS EM ORDEM DECRESCENTE DE NOTAS. MAX 100 NOMES}
USES TARDENOITE;
VAR NOME:ARRAY[1..100] OF STRING[35];
    NOTA:ARRAY[1..100] OF INTEGER;
    NOL:STRING[35];
    NTL,A,AUX1,TOT,C,B:INTEGER;
    AUX2:STRING[35];
    TROCA:BOOLEAN;
Begin
 WRITE('NOME=>');
 READLN(NOL);
 NOL:=UPCASE(NOL) ;
 WHILE(NOL<>'FIM') DO
  BEGIN
   C:=C+1;
   NOME[C]:=NOL;
   LEIA('NOTA=>',NTL);
   NOTA[C]:=NTL;
   WRITE('NOME=>');
   READLN(NOL);
   NOL:=UPCASE(NOL) ;
  END;
//INICIO DA ORDENACAO
 TOT:=C;
 REPEAT
  TOT:=TOT-1;
  TROCA:=TRUE;
  FOR A:=1 TO TOT DO
   IF(NOTA[A]>NOTA[A+1])THEN
    BEGIN
     AUX1:=NOTA[A];
     NOTA[A]:=NOTA[A+1];
     NOTA[A+1]:=AUX1;
     TROCA:=FALSE;
     AUX2:=NOME[A];
     NOME[A]:=NOME[A+1];
     NOME[A+1]:=AUX2;
    END;
  UNTIL TROCA;
//FIM DA ORDENAÇÃO
//MOSTRAR
 FOR B:=C DOWNTO 1 DO
  WRITELN(NOME[B]:50,'  ',NOTA[B]:4);
 TERMINE;     
End.